Global Components : Header and Navigation Bar done
BT3103AppDev1/l1-final-project-group-10 pull request #8
Opened 2023-03-18 05:21 UTC by lihuicham

Completed Header and Navigation Bar. 
Active class added.

2023-03-22 08:17 UTC, xbrianlong requested changes
Generally looks good except for a few design intricacies.

Change merge target to dev branch.

Things missing that needed to be added in the future:
-Clicking avatar goes to user profile page/ modal
-Expand Map, Share, Edit functionalities from ItineraryHeader
-Delete functionality + clicking brings up LocationCard functionality from DestinationItem

2023-03-22 08:29 UTC, xbrianlong commented on src/components/ItineraryPage/ItineraryHeader.vue
I realised u push a separate PR for itinerary page so u can ignore this if u fixed it in the new PR. Just fix the navbar problems first then i can merge this branch first.

2023-03-22 09:33 UTC, lihuicham commented on src/components/ItineraryPage/ItineraryHeader.vue
yes, it is fixed in another PR for itinerary page already ! thanks !

2023-03-22 09:35 UTC, lihuicham commented on src/components/ItineraryPage/ItineraryHeader.vue
for this pull request, can just look at the header and nav bar - the itinerary page design is in another PR. but, yes, i am working and will continue work on the interactivity of the itinerary page.

2023-03-27 04:30 UTC, lihuicham commented on src/components/GlobalComponents/NavigationBar.vue
okay, got it ! fixed alr

2023-03-27 04:31 UTC, merged